client_id = "d8e86b3cf5b1deb9ed0cf04d5fc7473c"
name = "Private Club"
handle = "digital-passport-private-club"
application_url = "https://shub-uk.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "read_products,write_products,read_customers,read_orders,read_content,write_content"

[auth]
redirect_urls = [
  "https://shub-uk.com/auth/callback",
  "https://shub-uk.com/auth/shopify/callback"
]

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/app-uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/products"
  topics = [ "products/update", "products/delete" ]

[pos]
embedded = false
